spring:
  application:
    name: jobweaver-scheduler

  datasource:
    url: jdbc:postgresql://localhost:5432/jobweaver
    username: jobweaver
    password: jobweaver

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    locations: classpath:db/migration

  kafka:
    bootstrap-servers: localhost:9092

app:
  kafka:
    topics:
      job-created: job-created
      job-completed: job-completed
      job-failed: job-failed
      run-job: run-job
      job-dead-letter: job-dead-letter

management:
  endpoints:
    web:
      exposure:
        include: health,info
