spring:
  application:
    name: jobweaver-worker

  datasource:
    url: jdbc:postgresql://localhost:5434/jobweaver_worker
    username: jobweaver
    password: jobweaver

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    locations: classpath:db/migration

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: jobweaver-workers

server:
  port: 8082

app:
  kafka:
    topics:
      run-job: run-job
      job-completed: job-completed
      job-failed: job-failed

management:
  endpoints:
    web:
      exposure:
        include: health,info

---
spring:
  config:
    activate:
      on-profile: docker

  datasource:
    url: jdbc:postgresql://postgres-worker:5432/jobweaver_worker

  kafka:
    bootstrap-servers: kafka:29092
